config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'welcome#welcome'

  get '/team', to: 'team#team'

  get '/contact', to: 'contact#contact'

  get '/welcome/:first_name', to: 'welcome#welcome'

  get '/welcome', to: 'welcome#welcome'

  get '/gossip/:id', to: 'gossip#gossip', as: 'gossip'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def contact
    
  end

end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def gossip
    @gossip = Gossip.find(params[:id])
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController

 def team

 end
 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def welcome
    @first_name = params[:first_name]
    @id = Gossip.first.id
    puts @id

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/contact.html.erb
<h1 class="text-center">ça c'est les contacts</h1>
<br />
<p><strike> putain de ses morts: 3h pour claquer 2 pages à la con sur un serveur local </strike></p>

<h4><i>Pour contacter la Team Lille de THP:</i></h4>

<ul>
  <li> Par email: <a href="mailto:thehackingproject@gmail.com"> thehackingproject@gmail.com</a></li>
  <li> sur le Slack: <a href="https://thehackingproject.slack.com/messages/C5XS0SCF2/"> #lieu-lille</a></li>
</ul>

app/views/gossip/gossip.html.erb
<p> Le gossip n°<%= @gossip.id%> </p>
<p> <%= @gossip.content%> </p>
<p> <i> Auteur: <%= @gossip.author %> </i> </p>

<%= link_to "Retour à l'Accueil", welcome_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/welcome">Accueil <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/team">Team</a>
      </li>
    </ul>
  </div>
</nav>


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/team/team.html.erb
<div class="container-fluid p-3 mb-2 bg-warning text-dark">
  <h1 align="center"> TEAM LILLE !!!</h1>
</div>

<p align="center"><a href="http://www.noelshack.com/2018-44-2-1540919741-teamlille.jpg">
  <img src="http://image.noelshack.com/minis/2018/44/2/1540919741-teamlille.png" WIDTH=30% />
</a></p>

<ul>
  <li>Anaïs</li>
  <li>Virginie</li>
  <li>Josh</li>
  <li>Mouss'</li>
  <li>Félix</li>
  <li>Rafik</li>
  <li>Clément</li>
  <li>Tony</li>
  <li>Thomas</li>
</ul>

app/views/welcome/welcome.html.erb
<h1 align="center"> Bienvenue <%= @first_name %> ! </h1>

<br>

<p>Ici c'est notre super site de potins, il est chouette, non ?</p>

<p> Voici la liste des derniers potins: </p>

<% Gossip.all.each do |gossip| %>

<div class="card border-light mb-3" style="max-width: 18rem;">
  <div class="card-header">Le gossip n°<%= gossip.id%></div>
  <div class="card-body">
    <h5 class="card-title"><i><%= gossip.author %> </i></h5>
    <p class="card-text"><%= gossip.content%> <br> Pour voir le gossip <%= link_to "Clique ici", gossip_path(gossip.id) %> </div>
</div>

<% end %>